### ISSUE TITLE
Bug: Broker Overgangslønsing Download feiler når useManifestShim=true

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#600]
Vi opplever feil i overgangnsløsning når manifest-generering er påskrudd.

## Repro steps
- Bruk Broker Overgangsløsning "altinn-broker-test-resource-2" 
- Aktiver useManifestShim=true, som gjør at manifest.xml genereres ved download.
- Kall Altinn 2 SOAP API med SOAPUI
- Initialize + UploadFile OK
- DownloadFile får ikke respons: "SocketException: Connection reset"

For samme tjeneste/config fungerer det OK med useManifestShim=false.

Følgende feilmelding logges i Altinn 2 sine logger:
> Timestamp: 29.11.2024 11:38:02
> Message: Value cannot be null.
> Parameter name: DownloadFileStreamedBasicResult
> Category: APPLICATION
> Priority: -1
> EventId: 0
> Severity: Error
> Title:
> Machine: at24-app03
> Application Domain: /LM/W3SVC/10003/ROOT/ServiceEngineExternal-1-133773436397504202
> Process Id: 7208
> Process Name: c:\windows\system32\inetsrv\w3wp.exe
> Win32 Thread Id: 7572
> Thread Name: 17
> ErrorMessages: System.ArgumentNullException: Value cannot be null.
> Parameter name: DownloadFileStreamedBasicResult
>    at System.ServiceModel.Dispatcher.StreamFormatter.GetStreamAndWriteStartWrapperIfNecessary(XmlDictionaryWriter writer, Object[] parameters, Object returnValue)
>    at System.ServiceModel.Dispatcher.StreamFormatter.Serialize(XmlDictionaryWriter writer, Object[] parameters, Object returnValue)
>    at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
>    at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
>    at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
>    at System.ServiceModel.Channels.MtomMessageEncoder.WriteMessage(Message message, Stream stream, String startInfo, String boundary, String startUri, Boolean writeMessageHeaders)
>    at System.ServiceModel.Channels.HttpOutput.WriteStreamedMessage(TimeSpan timeout)
>    at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
>    at System.ServiceModel.Channels.HttpPipeline.EmptyHttpPipeline.SendReplyCore(Message message, TimeSpan timeout)
>    at System.ServiceModel.Channels.HttpPipeline.EmptyHttpPipeline.SendReply(Message message, TimeSpan timeout)
>    at System.ServiceModel.Channels.HttpRequestContext.OnReply(Message message, TimeSpan timeout)
>    at System.ServiceModel.Activation.HostedHttpContext.OnReply(Message message, TimeSpan timeout)
>    at System.ServiceModel.Channels.RequestContextBase.Reply(Message message, TimeSpan timeout)
>    at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.Reply(MessageRpc& rpc)
> Log invoking method: Altinn.Common.WCF.ErrorHandler.HandleError

Ved test i POSTMAN direkte mot LegacyFileController får vi HTTP 500 Server error, som forsvinner hvis vi flipper useManifestShim tilbake til "false".

Så det kan virke som både feil i LegacyFileController + en bug i hvordan Altinn 2 Brokerbridge håndterer feilen.

Issue #601 brukes til å tracke status for Altinn 2 kodendring.

### Eksempel på fil i Staging
>Recfipient: 0192:313559017
>fileid: 22cd2069-ba23-41c4-9314-4de0cb1675e7

Mulig feil i håndtering av Manifest.xml?

**Comment by RagnarFatland-Avanade** [comment]
@tomshag regger bug for fix av Altinn 2 feilhåndtering.

**Comment by RagnarFatland-Avanade** [comment]
Verifisert OK i TT02.
